# Generated by Django 5.2.8 on 2025-12-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=200)),
                ('rec_desc', models.TextField()),
                ('rec_images', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
