# Generated by Django 5.2.8 on 2025-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='rec_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
